In [15]:
import numpy as np
import pandas as pd



In [16]:
rawdataset = pd.read_csv('medinsur.csv')
rawdataset['smoker'] = rawdataset['smoker'].replace({'yes' : 1, 'no' : 0})
rawdataset

age     sex     bmi  children  smoker     region    charges
0      19  female  27.900         0       1  southwest  16884.920
1      18    male  33.770         1       0  southeast   1725.552
2      28    male  33.000         3       0  southeast   4449.462
3      33    male  22.705         0       0  northwest  21984.470
4      32    male  28.880         0       0  northwest   3866.855
...   ...     ...     ...       ...     ...        ...        ...
1333   50    male  30.970         3       0  northwest  10600.550
1334   18  female  31.920         0       0  northeast   2205.981
1335   18  female  36.850         0       0  southeast   1629.834
1336   21  female  25.800         0       0  southwest   2007.945
1337   61  female  29.070         0       1  northwest  29141.360

[1338 rows x 7 columns]

In [17]:
maledataset = rawdataset[rawdataset['sex'] == 'male']

Xmale = maledataset[['age', 'bmi', 'children']].values

ymale = maledataset.iloc[:, 4].values

ymale

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(Xmale,
                                                   ymale,
                                                   test_size = 0.25,
                                                   random_state = 0)

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [20]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [21]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred. reshape(len(y_pred), 1)
                     , y_test.reshape(len(y_test), 1))
                    ,1))

[[0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)

accuracy_score(y_test, y_pred)

[[131   0]
 [ 38   0]]


0.7751479289940828

In [23]:
b0 = classifier.intercept_[0]
b1 = classifier.coef_[0][0]
b2 = classifier.coef_[0][1]
b3 = classifier.coef_[0][2]

print(f"Logistic Regression Model Equation: P(Y=1) = 1 / (1 + e^(-({b0:.4f} + {b1:.4f} * age + {b2:.4f} * bmi + {b3:.4f}* children)))")

Logistic Regression Model Equation: P(Y=1) = 1 / (1 + e^(-(-1.1646 + -0.0447 * age + 0.0653 * bmi + 0.1096* children)))


In [24]:
def smokerprob(age, bmi, children):
    p = 1 / (1 + 2.718281828459045**(-(-1.1646 + -0.0447 * age + 0.0653 * bmi + 0.1096* children)))
    print(p)

In [26]:
smokerprob(25, 23, 5)

0.4422094240706156


In [12]:
from matplotlib.colors import ListedColormap
import matplotlib.pyplot as plt

X_set, y_set = sc.inverse_transform(X_train), y_train

X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10
                              , stop = X_set[:, 0].max() + 10
                              , step = 0.25)
                    , np.arange(start = X_set[:, 1]. min() - 1000
                               , stop = X_set[:, 1].max() + 1000
                               , step = 0.25))

plt.contourf(X1
            , X2
            , classifier.predict(sc.transform(np.array([X1.ravel()
                                                       , X2.ravel()]).T)).reshape(X1.shape)
            , alpha = 0.75
            , cmap = ListedColormap(('salmon', 'dodgerblue')))

plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())

for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0]
               , X_set[y_set == j, 1]
               , color = ListedColormap(('red', 'blue'))(i)
               , label = j)
    
plt.title('Logistic Regression (Training set)')
plt.xlabel('Age')

plt.ylabel('Estimated Salary')

plt.legend()
plt.show()

ValueError: X has 2 features, but StandardScaler is expecting 3 features as input.