In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score


In [2]:
df = pd.read_csv('medinsur.csv')
df['smoker'] = df['smoker'].replace({'yes' : 1, 'no': 0})
df

age     sex     bmi  children  smoker     region    charges
0      19  female  27.900         0       1  southwest  16884.920
1      18    male  33.770         1       0  southeast   1725.552
2      28    male  33.000         3       0  southeast   4449.462
3      33    male  22.705         0       0  northwest  21984.470
4      32    male  28.880         0       0  northwest   3866.855
...   ...     ...     ...       ...     ...        ...        ...
1333   50    male  30.970         3       0  northwest  10600.550
1334   18  female  31.920         0       0  northeast   2205.981
1335   18  female  36.850         0       0  southeast   1629.834
1336   21  female  25.800         0       0  southwest   2007.945
1337   61  female  29.070         0       1  northwest  29141.360

[1338 rows x 7 columns]

In [3]:
male_data = df[df['sex'] == 'male']

female_data = df[df['sex'] == 'female']

male_data
female_data

age     sex    bmi  children  smoker     region    charges
0      19  female  27.90         0       1  southwest  16884.920
5      31  female  25.74         0       0  southeast   3756.622
6      46  female  33.44         1       0  southeast   8240.590
7      37  female  27.74         3       0  northwest   7281.506
9      60  female  25.84         0       0  northwest  28923.140
...   ...     ...    ...       ...     ...        ...        ...
1332   52  female  44.70         3       0  southwest  11411.690
1334   18  female  31.92         0       0  northeast   2205.981
1335   18  female  36.85         0       0  southeast   1629.834
1336   21  female  25.80         0       0  southwest   2007.945
1337   61  female  29.07         0       1  northwest  29141.360

[662 rows x 7 columns]

In [4]:
xmale = male_data[["age","bmi","children"]].values
ymale = male_data.iloc[:,4].values

ymale

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [5]:
xfemale = female_data[["age","bmi","children"]].values
yfemale = female_data.iloc[:,4].values

xfemale

array([[19.  , 27.9 ,  0.  ],
       [31.  , 25.74,  0.  ],
       [46.  , 33.44,  1.  ],
       ...,
       [18.  , 36.85,  0.  ],
       [21.  , 25.8 ,  0.  ],
       [61.  , 29.07,  0.  ]])

In [6]:
x_train, x_test, y_train, y_test = train_test_split(xmale,ymale,test_size = 0.25, 
                                                    random_state=0)
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [7]:
#for Female
xf_train, xf_test, yf_train, yf_test = train_test_split(xfemale,yfemale,test_size = 0.25, 
                                                    random_state=0)
sc = StandardScaler()
xf_train = sc.fit_transform(xf_train)
xf_test = sc.transform(xf_test)

In [8]:
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)
#for female
classifierfe = LogisticRegression(random_state = 0)
classifierfe.fit(xf_train, yf_train)

LogisticRegression(random_state=0)

In [9]:
#for male
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)



[[131   0]
 [ 38   0]]


In [10]:
print('accuracy for Male: ', accuracy_score(y_test, y_pred))

accuracy for Male:  0.7751479289940828


In [11]:
#for Female 
yf_pred = classifierfe.predict(xf_test)
cmf = confusion_matrix(yf_test, yf_pred)
print(cmf)



[[133   0]
 [ 33   0]]


In [12]:
print('accuracy for Female: ', accuracy_score(yf_test, yf_pred))

accuracy for Female:  0.8012048192771084


In [13]:
b0 = classifier.intercept_[0]
b1 = classifier.coef_[0][0]
b2 = classifier.coef_[0][1]
b3 = classifier.coef_[0][2]

print(f"Model Equation (For Male): P(Y=1) = 1 / (1 + e^(-({b0:.4f} + {b1:.4f} * age + {b2:.4f} * bmi + {b3:.4f}* children)))")

Model Equation (For Male): P(Y=1) = 1 / (1 + e^(-(-1.1646 + -0.0447 * age + 0.0653 * bmi + 0.1096* children)))


In [14]:
b0f = classifierfe.intercept_[0]
b1f = classifierfe.coef_[0][0]
b2f = classifierfe.coef_[0][1]
b3f = classifierfe.coef_[0][2]

print(f"Model Equation (For Female): P(Y=1) = 1 / (1 + e^(-({b0f:.4f} + {b1f:.4f} * age + {b2f:.4f} * bmi + {b3f:.4f}* children)))")

Model Equation (For Female): P(Y=1) = 1 / (1 + e^(-(-1.6287 + -0.0828 * age + -0.1135 * bmi + -0.0745* children)))


In [ ]:
def smokerprobmale (age, bmi, children):
    X1 = age
    X2 = bmi
    X3 = children
    under = -(b0 + b1*X1 + b2*X2 + b3*X3)
    probability = 1 / (1 + np.exp(under))
    return probability


age = float(input("Enter your Age here: "))
bmi = float(input("Enter your bmi here: "))
child = float(input("Enter your child here: "))

percentage = smokerprobmale (age, bmi, child)
print(percentage)
print(f"Probability of IDK {100*percentage:.4f}")

In [ ]:
def smokerprobmale (age, bmi, children):
    X1 = age
    X2 = bmi
    X3 = children
    under = -(b0 + b1*X1 + b2*X2 + b3*X3)
    probability = 1 / (1 + np.exp(under))
    return probability

print(b0, b1, b2, b3)
age = float(input("Enter your Age here: "))
bmi = float(input("Enter your bmi here: "))
child = float(input("Enter your child here: "))

percentage = smokerprobmale (age, bmi, child)
print(percentage)
print(f"Probability of IDK {100*percentage:.4f}")

In [ ]:
def smokerprobfemale (age, bmi, children):
    X1 = age
    X2 = bmi
    X3 = children
    under = -(b0f + b1f*X1 + b2f*X2 + b3f*X3)
    probability = 1 / (1 + np.exp(under))
    return probability


age = float(input("Enter your Age here: "))
bmi = float(input("Enter your bmi here: "))
child = float(input("Enter your child here: "))

percentage = smokerprobfemale (age, bmi, child)
print(percentage)
print(f"Probability of IDK {100*percentage:.4f}")